# General parameters
general:

    demultiplex_protocol: "GAGE-seq"
    
    # Full path to fastq_info.txt, with experiment/plate name in first column and corresponding FASTQ directory in second column
    fastq_info: "/path/to/map3C_run/txt/plate_info.txt"

    # Full path to where output data will be placed
    output_directory: "/path/to/map3C_run/demultiplex"

demultiplex_protocols:

    GAGE-seq:

        BC1:

            barcodes: "/path/to/map3C_run/txt/barcodes_BC1.fa"

            cutadapt_params: "-e 1"

        BC2:
            
            barcodes: "/path/to/map3C_run/txt/barcodes_BC2.fa"

            cutadapt_params: "-e 1"
