

mask_protocol = config["read_analysis"]["mask"]["mask_protocol"]

if mask_protocol == "default":

    if not bam_generated:

        raise Exception("BAM file must be generated by map3C call-contacts. Remove the --no-output-bam flag from this command in the config file.")

    include: "mask.smk"

coord_sort_bam_protocol = config["read_analysis"]["coord_sort_bam"]["coord_sort_bam_protocol"]

if coord_sort_bam_protocol == "default":

    if not bam_generated:

        raise Exception("BAM file must be generated by map3C call-contacts. Remove the --no-output-bam flag from this command in the config file.")

    include: "coord_sort_bam.smk"

allc_protocol = config["read_analysis"]["allc"]["allc_protocol"]

if allc_protocol == "default":

    if not bam_generated:

        raise Exception("BAM file must be generated by map3C call-contacts. Remove the --no-output-bam flag from this command in the config file.")

    if not coord_sort_bam_done:

        raise Exception("BAM file must be coordinate-sorted. Turn this on in the config file.")

    if mode == "bsdna":

        include: "allc.smk"



