
mask_protocol = config["read_analysis"]["mask"]["mask_protocol"]

if mask_protocol == "default":

    if not bam_generated:

        raise Exception("BAM file must be generated by map3C call-contacts. Remove the --no-output-bam flag from this command in the config file.")

    include: "mask.smk"

allc_protocol = config["read_analysis"]["allc"]["allc_protocol"]

if allc_protocol == "default":

    if not bam_generated:

        raise Exception("BAM file must be generated by map3C call-contacts. Remove the --no-output-bam flag from this command in the config file.")

    if mode == "bsdna":

        include: "allc.smk"




